[build]
  base = "/"
  publish = "client/build"
  command = "npm install && cd client && npm install && npm run build"
  functions = "functions"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
